version: "3.9"

services:
  postgres:
    image: "postgres"
    container_name: "payload-pg"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "postgres"
    restart: always
    volumes:
      - pgdata:/data/postgres

  payload-sys: 
    build: .
    container_name: "payload-app"
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/src/payloadsys
    restart: always
    links: 
      - postgres
    depends_on:
      - postgres

volumes:
  pgdata:
    driver: local
