version: "3.9"

services:
  postgres:
    image: "postgres"
    container_name: "payload-pg"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "postgres"
    restart: always
    volumes:
      - pgdata:/data/postgres

  cache:
    image: redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    ports:
      - 6380:6379
    volumes:
      - cache:/data

  payload-sys: 
    build: .
    container_name: "payload-app"
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/src/payloadsys
    restart: always
    links: 
      - postgres
      - cache
    depends_on:
      - postgres
      - cache
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: password

volumes:
  pgdata:
    driver: local
  cache:
    driver: local
