version: "3.9"

services:
  postgres:
    image: "postgres"
    container_name: "accs-pg"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "postgres"

  app: 
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/src/app