version: "3.9"

services:
  postgres:
    image: "postgres:14.2-alpine"
    container_name: "payload-pg"
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    volumes:
      - pgdata:/data/postgres
    networks:
      - payloadNet

  cache:
    image: redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    ports:
      - 6379:6379
    volumes:
      - cache:/data
    networks:
      - payloadNet

  payload-sys: 
    build: .
    container_name: "payload-app"
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - .:/src/payloadsys
    restart: always
    links: 
      - postgres
      - cache
    depends_on:
      - postgres
      - cache
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: password
    networks:
      - payloadNet

volumes:
  pgdata:
    driver: local
  cache:
    driver: local

networks:
  payloadNet:
    driver: bridge