name: CI

on: 
  push: 
    branches: [ main ]
  
  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest
  
    steps: 
      - uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with: 
          node-version: 18.x
          
      - name: Install Dependencies
        run: yarn 
      
      - name: Test printing your secret (Remove this step in production)
        run: cat $HOME/secrets/SSH_KEY.json
        
      - name: Connect aws
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "., !node_modules"
          target: "test"
    
  
